#!/bin/bash
# Lelu One-Command Installer
# Usage: curl -fsSL https://lelu-ai.com/install.sh | bash

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

echo ""
echo -e "${BOLD}🚀 Lelu Installer${NC}"
echo ""

# Check if Docker is installed
echo -e "${CYAN}Checking for Docker...${NC}"
if ! command -v docker &> /dev/null; then
    echo ""
    echo -e "${RED}❌ Docker not found${NC}"
    echo ""
    echo -e "${YELLOW}Lelu requires Docker to run the full stack with UI.${NC}"
    echo ""
    echo -e "${BOLD}Install Docker:${NC}"
    echo "  • Mac:     https://docs.docker.com/desktop/install/mac-install/"
    echo "  • Windows: https://docs.docker.com/desktop/install/windows-install/"
    echo "  • Linux:   https://docs.docker.com/engine/install/"
    echo ""
    echo -e "${BOLD}Or use CLI-only mode:${NC}"
    echo -e "  ${CYAN}npm install -g @lelu-auth/lelu${NC}"
    echo -e "  ${CYAN}lelu audit-log${NC}"
    echo ""
    exit 1
fi

if ! command -v docker-compose &> /dev/null; then
    echo ""
    echo -e "${RED}❌ docker-compose not found${NC}"
    echo ""
    echo -e "${YELLOW}Please install docker-compose:${NC}"
    echo "  https://docs.docker.com/compose/install/"
    echo ""
    exit 1
fi

echo -e "${GREEN}✅ Docker found${NC}"
echo ""

# Download docker-compose.yml
echo -e "${CYAN}📦 Downloading Lelu stack...${NC}"
if [ ! -f "docker-compose.yml" ]; then
    curl -fsSL https://raw.githubusercontent.com/lelu-auth/lelu/main/docker-compose.yml -o docker-compose.yml
    echo -e "${GREEN}✅ Downloaded docker-compose.yml${NC}"
else
    echo -e "${GREEN}✅ docker-compose.yml already exists${NC}"
fi

echo ""

# Create .env file
if [ ! -f ".env" ]; then
    echo -e "${CYAN}📝 Creating .env file...${NC}"
    cat > .env << 'EOF'
# Lelu Configuration
# Generated by: curl -fsSL https://lelu-ai.com/install.sh | bash

# Engine Configuration
API_KEY=lelu-dev-key
JWT_SIGNING_KEY=change-me-in-production
LELU_MODE=enforce

# Platform Configuration
PLATFORM_API_KEY=platform-dev-key
POSTGRES_PASSWORD=lelu-dev-secret

# Client Configuration (for your app)
LELU_ENGINE_URL=http://localhost:8083
LELU_PLATFORM_URL=http://localhost:9091
LELU_API_KEY=lelu-dev-key
EOF
    echo -e "${GREEN}✅ Created .env file${NC}"
else
    echo -e "${GREEN}✅ .env file already exists${NC}"
fi

echo ""

# Start services
echo -e "${CYAN}🔧 Starting Lelu services...${NC}"
echo -e "${YELLOW}This may take a minute on first run...${NC}"
echo ""

docker-compose up -d

echo ""
echo -e "${CYAN}⏳ Waiting for services to be ready...${NC}"
sleep 10

echo ""
echo -e "${GREEN}✨ Lelu is ready!${NC}"
echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BOLD}📊 Web UI:        http://localhost:3002${NC}"
echo -e "${BOLD}🔧 Engine API:    http://localhost:8083${NC}"
echo -e "${BOLD}📝 Platform API:  http://localhost:9091${NC}"
echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BOLD}Next steps:${NC}"
echo -e "  ${CYAN}1. Open http://localhost:3002 in your browser${NC}"
echo -e "  ${CYAN}2. Install SDK: npm install @lelu-auth/lelu${NC}"
echo -e "  ${CYAN}3. View docs: http://localhost:3002/docs${NC}"
echo ""
echo -e "${BOLD}Useful commands:${NC}"
echo -e "  ${CYAN}docker-compose ps        # Check service status${NC}"
echo -e "  ${CYAN}docker-compose logs -f   # View logs${NC}"
echo -e "  ${CYAN}docker-compose down      # Stop services${NC}"
echo ""
