# Lelu One-Command Installer for Windows
# Usage: iwr -useb https://lelu-ai.com/install.ps1 | iex

$ErrorActionPreference = "Stop"

# Colors
function Write-ColorOutput($ForegroundColor) {
    $fc = $host.UI.RawUI.ForegroundColor
    $host.UI.RawUI.ForegroundColor = $ForegroundColor
    if ($args) {
        Write-Output $args
    }
    $host.UI.RawUI.ForegroundColor = $fc
}

Write-Host ""
Write-ColorOutput Cyan "🚀 Lelu Installer"
Write-Host ""

# Check if Docker is installed
Write-ColorOutput Cyan "Checking for Docker..."
try {
    $dockerVersion = docker --version 2>$null
    $dockerComposeVersion = docker-compose --version 2>$null
    if (-not $dockerVersion -or -not $dockerComposeVersion) {
        throw "Docker not found"
    }
    Write-ColorOutput Green "✅ Docker found"
} catch {
    Write-Host ""
    Write-ColorOutput Red "❌ Docker not found"
    Write-Host ""
    Write-ColorOutput Yellow "Lelu requires Docker to run the full stack with UI."
    Write-Host ""
    Write-ColorOutput White "Install Docker:"
    Write-Host "  • Windows: https://docs.docker.com/desktop/install/windows-install/"
    Write-Host ""
    Write-ColorOutput White "Or use CLI-only mode:"
    Write-ColorOutput Cyan "  npm install -g @lelu-auth/lelu"
    Write-ColorOutput Cyan "  lelu audit-log"
    Write-Host ""
    exit 1
}

Write-Host ""

# Download docker-compose.yml
Write-ColorOutput Cyan "📦 Downloading Lelu stack..."
if (-not (Test-Path "docker-compose.yml")) {
    try {
        Invoke-WebRequest -Uri "https://raw.githubusercontent.com/lelu-auth/lelu/main/docker-compose.yml" -OutFile "docker-compose.yml"
        Write-ColorOutput Green "✅ Downloaded docker-compose.yml"
    } catch {
        Write-ColorOutput Red "❌ Failed to download: $_"
        Write-ColorOutput Yellow "Please download manually from:"
        Write-Host "https://raw.githubusercontent.com/lelu-auth/lelu/main/docker-compose.yml"
        exit 1
    }
} else {
    Write-ColorOutput Green "✅ docker-compose.yml already exists"
}

Write-Host ""

# Create .env file
if (-not (Test-Path ".env")) {
    Write-ColorOutput Cyan "📝 Creating .env file..."
    $envContent = @"
# Lelu Configuration
# Generated by: iwr -useb https://lelu-ai.com/install.ps1 | iex

# Engine Configuration
API_KEY=lelu-dev-key
JWT_SIGNING_KEY=change-me-in-production
LELU_MODE=enforce

# Platform Configuration
PLATFORM_API_KEY=platform-dev-key
POSTGRES_PASSWORD=lelu-dev-secret

# Client Configuration (for your app)
LELU_ENGINE_URL=http://localhost:8083
LELU_PLATFORM_URL=http://localhost:9091
LELU_API_KEY=lelu-dev-key
"@
    Set-Content -Path ".env" -Value $envContent
    Write-ColorOutput Green "✅ Created .env file"
} else {
    Write-ColorOutput Green "✅ .env file already exists"
}

Write-Host ""

# Start services
Write-ColorOutput Cyan "🔧 Starting Lelu services..."
Write-ColorOutput Yellow "This may take a minute on first run..."
Write-Host ""

try {
    docker-compose up -d
} catch {
    Write-ColorOutput Red "❌ Failed to start services"
    Write-ColorOutput Yellow "Try running manually: docker-compose up -d"
    exit 1
}

Write-Host ""
Write-ColorOutput Cyan "⏳ Waiting for services to be ready..."
Start-Sleep -Seconds 10

Write-Host ""
Write-ColorOutput Green "✨ Lelu is ready!"
Write-Host ""
Write-ColorOutput White "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
Write-Host ""
Write-ColorOutput White "📊 Web UI:        http://localhost:3002"
Write-ColorOutput White "🔧 Engine API:    http://localhost:8083"
Write-ColorOutput White "📝 Platform API:  http://localhost:9091"
Write-Host ""
Write-ColorOutput White "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
Write-Host ""
Write-ColorOutput White "Next steps:"
Write-ColorOutput Cyan "  1. Open http://localhost:3002 in your browser"
Write-ColorOutput Cyan "  2. Install SDK: npm install @lelu-auth/lelu"
Write-ColorOutput Cyan "  3. View docs: http://localhost:3002/docs"
Write-Host ""
Write-ColorOutput White "Useful commands:"
Write-ColorOutput Cyan "  docker-compose ps        # Check service status"
Write-ColorOutput Cyan "  docker-compose logs -f   # View logs"
Write-ColorOutput Cyan "  docker-compose down      # Stop services"
Write-Host ""

# Open browser
$openBrowser = Read-Host "Open browser now? (Y/n)"
if ($openBrowser -ne "n" -and $openBrowser -ne "N") {
    Write-Host ""
    Write-ColorOutput Cyan "🌐 Opening browser..."
    Start-Process "http://localhost:3002"
}

Write-Host ""
