apiVersion: v1
kind: Secret
metadata:
  name: lelu-secrets
  labels:
    app.kubernetes.io/name: lelu
type: Opaque
stringData:
  engineJwtSigningKey: {{ .Values.secrets.engine.jwtSigningKey | quote }}
  engineCpHmacSecret: {{ .Values.secrets.engine.cpHmacSecret | quote }}
  platformApiKey: {{ .Values.secrets.platform.apiKey | quote }}
  platformDatabaseUrl: {{ .Values.secrets.platform.databaseUrl | quote }}
  uiPlatformApiKey: {{ .Values.secrets.ui.platformApiKey | quote }}
  postgresPassword: {{ .Values.secrets.postgres.password | quote }}
